### ISSUE TITLE
Feature request: Have a more consise format

### ISSUE THREAD

**Issue by olibre** [clarketm/pprintjson#2]
Thank you for you sweet JSON printer, I am using and enjoying it. 🤩
But, `pprintjson` often uses unnecessary room and I request an option to get a more concise display.

You may be inspired from file [`prettyjson.py`](https://github.com/andy-gh/pygrid/blob/master/prettyjson.py) described in [that SO answer](https://stackoverflow.com/a/56497521/938111).

Example of a *concise* representation converted to an *unnecessary* verbose one:

```yaml
$ pprintjson -c '
{
  "grid": {"port": "COM5"},
  "policy": {
    "movingaverage": 5,
    "hysteresis": 5,
    "fan1": {
      "name": "CPU",
      "signal": "cpu",
      "mode": "auto",
      "speed": 100,
      "curve": [[0, 75], [50, 75], [75, 100]]
    }
  }
}'
```

```yaml
{
    "grid": {
        "port": "COM5"
    },
    "policy": {
        "movingaverage": 5,
        "hysteresis": 5,
        "fan1": {
            "name": "CPU",
            "signal": "cpu",
            "mode": "auto",
            "speed": 100,
            "curve": [
                [
                    0,
                    75
                ],
                [
                    50,
                    75
                ],
                [
                    75,
                    100
                ]
            ]
        }
    }
}
```
